[tool.poetry]
name = "snapbin"
version = "0.1.0"
description = "A little service to store and encrypt information, deleting it once it's retrieved."
authors = ["Andreas Zweili <andreas@zweili.ch>"]
license = "GPL3.0+"
readme = "README.org"

[tool.pylint."MESSAGES CONTROL"]
disable = [
    "missing-module-docstring",
    "missing-function-docstring",
    "missing-class-docstring",
]

[tool.poetry.dependencies]
python = "^3.11"
flask = "^3.0.0"
cryptography = "^42.0.4"
gunicorn = "^22.0.0"
peewee = "^3.17.6"


[tool.poetry.group.dev.dependencies]
python-lsp-server = "^1.9.0"
pytest = "^7.4.3"
pytest-cov = "^4.1.0"
mypy = "^1.8.0"
pylint = "^3.0.3"
freezegun = "^1.4.0"
black = "^24.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
