on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-snapbin-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: wimpysworld/nothing-but-nix@main
      - uses: cachix/install-nix-action@v31.3.0
      - name: Build snapbin image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: nix develop --command build-image.sh
