on:
  push:
    branches: [ "dev" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main", "dev" ]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: wimpysworld/nothing-but-nix@main
      - uses: cachix/install-nix-action@v31.3.0
      - name: Tests
        run: nix develop --command pytest --cov=snapbin tests.py

  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: wimpysworld/nothing-but-nix@main
      - uses: cachix/install-nix-action@v31.3.0
      - name: Tests
        run: nix develop --command pylint snapbin

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: wimpysworld/nothing-but-nix@main
      - uses: cachix/install-nix-action@v31.3.0
      - name: Tests
        run: nix develop --command mypy .
